### ISSUE TITLE
VolumeUp and VolumeDown functions do not work correctly

### ISSUE THREAD

**Issue by iliessens** [valentinalexeev/pdunehd#4]
The min() and max() functions in volumeUp and volumeDown should be swapped:
https://github.com/valentinalexeev/pdunehd/blob/91d608e96f6574e9b37360bdf91b3519c17f7806/pdunehd/__init__.py#L57

Currently the volumeUp function always jumps to max volume, and the volumeDown jumps to zero volume.

For consistency it might also be better to use volume_up and volume_down as names (snake case), but that might break downstream code.

**Comment by valentinalexeev** [comment]
Thank you for the ticket, @iliessens. LGTM.
